In [21]:
import csv
label = {}
with open('../data/GitHub_Aggregated.csv') as fp:
    reader = csv.DictReader(fp)
    for row in reader:
        concept = row['Concept']
        e, p, a = float(row['Evaluation_mean']), float(row['Potency_mean']), float(row['Activity_mean'])
        label[concept] = [round(d,3) for d in [e, p, a]]

In [22]:
warriner = {}
with open('../data/epa/Ratings_Warriner_et_al_epa') as fp:
    data = json.load(fp)
    for w in data.keys():
        epa = [data[w]['E'], data[w]['P'], data[w]['A']]
        warriner[w] = [round(d, 3) for d in epa]

In [46]:
import json
predict = {}
with open('../result/epa_expansion/nn/nn_result_github_all_2') as fp:
    predict = json.load(fp)
    for w in predict.keys():
        predict[w][2] = -predict[w][2]
        predict[w] = [round(d, 3) for d in predict[w]]

In [53]:
google = {}
with open('../result/epa_expansion/nn/nn_result_google_all_2') as fp:
    google = json.load(fp)
    for w in google.keys():
        google[w][2] = -google[w][2]
        google[w] = [round(d, 3) for d in google[w]]

In [48]:
wlist = wlist & set(google.keys())
wlist = set(label.keys()) & set(warriner.keys()) & set(predict.keys()) & set(google.keys())

In [49]:
print(len(label.keys()))
print(len(wlist))

587
363


In [50]:
wlist_warriner, wlist_label, wlist_pred, wlist_google = list(), list(), list(), list()
for w in wlist:
    wlist_warriner.append(warriner[w])
    wlist_label.append(label[w])
    wlist_pred.append(predict[w])
    wlist_google.append(google[w])
import numpy as np
wwarriner = np.array(wlist_warriner)
wlabel = np.array(wlist_label)
wpred = np.array(wlist_pred)
wgoogle = np.array(wlist_google)

In [51]:
mean = np.mean(np.abs(wlabel - wpred), axis=0)
print(mean)
rmse = np.sqrt(np.mean((wlabel - wpred) ** 2, axis=0))
print(rmse)

[0.97671074 0.52406887 0.58835262]
[1.14623334 0.71680493 0.75823703]


In [52]:
mean = np.mean(np.abs(wlabel - wgoogle), axis=0)
print(mean)
rmse = np.sqrt(np.mean((wlabel - wgoogle) ** 2, axis=0))
print(rmse)

[0.72942424 0.47921212 2.0896584 ]
[0.91564023 0.63858164 2.23367436]


In [27]:
mean = np.mean(np.abs(wlabel - wwarriner), axis=0)
print(mean)
rmse = np.sqrt(np.mean((wlabel - wwarriner) ** 2, axis=0))
print(rmse)

[0.78037741 2.25142424 0.95458953]
[0.96023418 2.4969333  1.15558275]


In [142]:
epa_dic = {}
for w in wlist:
    k = '%s %s %s' % (w, label[w], predict[w])
    epa_dic[k] = abs(label[w][0] - predict[w][0]) + abs(label[w][1] - predict[w][1]) \
    + abs(label[w][2] - predict[w][2])
from collections import OrderedDict
ordered_epa_dic = OrderedDict(sorted(epa_dic.items(), key=lambda x: x[1]))
for key in ordered_epa_dic:
    print(key)

popular [1.994, 1.919, 1.019] [1.952, 1.961, 0.847]
design [1.355, 1.594, 1.306] [1.348, 1.813, 1.222]
star [1.684, 1.506, 0.71] [1.576, 1.563, 0.858]
male [1.206, 1.252, 1.1] [1.019, 1.364, 1.185]
purpose [1.461, 1.879, 1.518] [1.418, 1.896, 1.171]
real [1.541, 1.503, 1.331] [1.5, 1.663, 1.026]
argument [-0.266, 0.734, 1.158] [0.125, 0.581, 1.192]
rude [-1.518, -0.732, 0.716] [-1.51, -0.342, 0.476]
strict [0.137, 1.103, 0.58] [0.287, 1.223, 0.958]
trigger [0.1, 1.044, 0.825] [-0.207, 1.012, 1.145]
author [1.668, 1.378, 1.135] [1.2, 1.475, 1.251]
system [1.314, 1.686, 1.429] [1.055, 1.746, 1.054]
upload [1.035, 1.139, 1.168] [0.782, 1.522, 1.1]
mature [1.75, 2.056, 1.526] [1.652, 2.043, 0.93]
initialize [1.234, 1.366, 1.276] [0.619, 1.44, 1.22]
return [1.22, 1.031, 0.943] [0.953, 1.219, 1.239]
celebrity [0.858, 1.121, 1.618] [0.405, 1.071, 1.369]
verbose [0.832, 1.132, 1.259] [0.726, 1.703, 1.183]
match [1.353, 1.368, 1.105] [0.752, 1.398, 1.246]
capable [2.004, 1.9, 1.296] [1.783, 2.3

In [37]:
def pprint(w):
    print('github, warriner, predict_github, predict_google')
    print([w, label[w], warriner[w], predict[w], google[w]])

In [116]:
for w in wlist:
    pprint(w)

['filter', [1.563, 0.807, 0.926], [-0.021, 1.036, 1.161]]
['clarify', [1.403, 0.847, 1.153], [0.449, 1.393, 1.509]]
['separate', [0.057, 0.403, 0.354], [0.022, 1.24, 1.847]]
['related', [1.306, 1.258, 0.884], [-0.688, -0.023, 1.105]]
['tricky', [-0.774, 0.365, 0.006], [-1.398, -0.684, 1.262]]
['broken', [-1.384, -0.445, -0.697], [-1.656, -1.376, 1.074]]
['compare', [1.126, 0.765, 0.771], [0.273, 1.264, 1.363]]
['quiet', [0.914, 0.184, -0.827], [-0.03, 1.495, 1.393]]
['prevent', [1.062, 0.656, 0.459], [0.171, 0.92, 0.64]]
['difficult', [-0.744, 0.325, 0.009], [-0.106, 0.963, 1.111]]
['compute', [1.443, 1.664, 0.889], [-0.055, 1.097, 1.343]]
['hobbyist', [1.397, 1.222, 0.962], [0.469, 1.232, 1.312]]
['legacy', [1.581, 1.375, 0.856], [0.055, 0.755, 1.574]]
['screen', [1.545, 1.529, 1.068], [1.742, 1.856, 1.609]]
['master', [1.236, 1.989, 1.471], [-0.316, 0.299, 1.149]]
['regular', [0.75, 0.571, 0.462], [1.34, 1.933, 1.983]]
['best', [2.088, 2.366, 1.544], [2.408, 2.59, 0.96]]
['push', [0.

In [38]:
pprint('quiet')

github, warriner, predict_github, predict_google
['quiet', [0.914, 0.184, -0.827], [1.863, -3.814, 1.396], [-0.03, 1.495, 1.393], [1.508, 2.093, -2.063]]


In [35]:
pprint('table')

['table', [0.987, 0.939, 0.845], [0.175, 0.697, 1.695], [0.895, 1.56, -2.077], [0.704, -2.355, 1.452]]


In [83]:
pprint('log')

['log', [1.5928571428571427, 1.1142857142857143, 0.9249999999999999], [-0.2841138541698456, 0.39939552545547485, -1.3712246417999268]]


In [32]:
pprint('generate')

[2.013888889, 1.669444444, 1.936111111]
[1.8015724420547485, 1.8645704984664917, 1.7159379720687866]


In [33]:
pprint('invalid')

[0.202777778, -0.233333333, 0.377777778]
[-2.757554769515991, -1.9528812170028687, 0.18231704831123352]


In [36]:
pprint('typo')

['typo', [-0.862, -0.314, -0.068], [-1.375, -1.101, 1.205], [-1.317, -1.117, -0.61], [-0.94, -0.966, -0.76]]


In [80]:
pprint('filter')

['filter', [1.562962962962963, 0.8074074074074075, 0.9259259259259262], [-0.02104046568274498, 1.0362566709518433, -1.1613062620162964]]


In [36]:
pprint('system')

[2.074285714, 2.428571429, 2.111428571]
[0.6514638066291809, 0.847267746925354, -0.19178053736686707]
