In [522]:
import csv
label = {}
label_std = {}
with open('../data/GitHub_Aggregated.csv') as fp:
    reader = csv.DictReader(fp)
    for row in reader:
        concept = row['Concept']
        e, p, a = float(row['Evaluation_mean']), float(row['Potency_mean']), float(row['Activity_mean'])
        label[concept] = [round(d,3) for d in [e, p, a]]
        e, p, a = float(row['Evaluation_std']), float(row['Potency_std']), float(row['Activity_std'])
        label_std[concept] = [round(d,3) for d in [e, p, a]]

In [442]:
warriner = {}
with open('../data/epa/Ratings_Warriner_et_al_epa_test') as fp:
    data = json.load(fp)
    for w in data.keys():
        epa = data[w]
        warriner[w] = [round(d, 3) for d in epa]

In [448]:
import json
predict = {}
with open('../result/epa_expansion/nn/nn_result_github_all_20') as fp:
    predict = json.load(fp)
    for w in predict.keys():
        predict[w] = [round(d, 3) for d in predict[w]]

In [444]:
google = {}
with open('../result/epa_expansion/nn/nn_result_google_all') as fp:
    google = json.load(fp)
    for w in google.keys():
        google[w] = [round(d, 3) for d in google[w]]

In [523]:
wlist = set(label.keys()) & set(warriner.keys()) & set(predict.keys()) & set(google.keys())

In [524]:
print(len(label.keys()))
print(len(wlist))

458
371


In [525]:
wlist_warriner, wlist_label, wlist_pred, wlist_google = list(), list(), list(), list()
std = list()
for w in wlist:
    wlist_warriner.append(warriner[w])
    wlist_label.append(label[w])
    wlist_pred.append(predict[w])
    wlist_google.append(google[w])
    std.append(label_std[w])
import numpy as np
wwarriner = np.array(wlist_warriner)
wlabel = np.array(wlist_label)
wpred = np.array(wlist_pred)
wgoogle = np.array(wlist_google)
wstd = np.array(std)

In [533]:
np.sum(np.abs(wlabel - wpred) < wstd, axis=0)

array([358, 353, 358])

In [527]:
np.sum(np.abs(wlabel - wgoogle) < wstd, axis=0)

array([352, 354, 342])

In [534]:
np.sum(np.abs(wlabel - wwarriner) < wstd, axis=0)

array([330, 308, 315])

In [486]:
def comp(label,warriner, pred, google):
    mean = np.mean(np.abs(wlabel - wwarriner), axis=0)
    print(mean)
    rmse = np.sqrt(np.mean((wlabel - wwarriner) ** 2, axis=0))
    print(rmse)
    print('========')
    mean = np.mean(np.abs(label - pred), axis=0)
    print(mean)
    rmse = np.sqrt(np.mean((label - pred) ** 2, axis=0))
    print(rmse)
    print('=========')
    mean = np.mean(np.abs(label - google), axis=0)
    print(mean)
    rmse = np.sqrt(np.mean((label - google) ** 2, axis=0))
    print(rmse)

In [528]:
comp(label=np.array(wlabel), warriner=np.array(wwarriner), pred=np.array(wpred), google=np.array(wgoogle))

[0.76352022 0.97025606 0.96969542]
[0.96184476 1.17527988 1.28103902]
[0.57341779 0.65952561 0.58084367]
[0.75709295 0.83389898 0.81257032]
[0.66039084 0.7457628  0.67232615]
[0.83460688 0.89292321 0.94437766]


In [502]:
def pprint(w):
    print('github, warriner, predict_github, predict_google')
    print([w, label[w], warriner[w], predict[w], google[w]])

In [515]:
for w in wlist:
    pprint(w)

github, warriner, predict_github, predict_google
['arrogant', [-2.173, -0.548, -1.527], [-2.809, -0.207, 0.632], [0.28, 1.039, -1.278], [-2.012, -0.719, 0.278]]
github, warriner, predict_github, predict_google
['important', [0.888, 1.636, -0.82], [2.277, 2.212, 0.021], [1.658, 2.226, -1.031], [1.966, 2.266, -0.611]]
github, warriner, predict_github, predict_google
['statement', [0.164, 0.621, -1.406], [0.503, 2.904, -1.382], [0.124, 0.883, -1.633], [1.099, 1.642, -1.504]]
github, warriner, predict_github, predict_google
['execute', [0.306, 0.791, -1.103], [-1.13, 0.346, 1.521], [0.297, 1.644, -1.505], [0.519, 1.665, -0.063]]
github, warriner, predict_github, predict_google
['override', [-0.366, 0.393, -1.355], [-0.668, 1.673, -1.869], [1.0, 1.553, -1.38], [0.188, 1.177, -1.252]]
github, warriner, predict_github, predict_google
['filter', [0.6, 0.4, -1.555], [0.716, 1.148, -1.494], [-0.021, 1.036, -1.161], [-0.05, 1.094, -1.708]]
github, warriner, predict_github, predict_google
['clean'

In [503]:
pprint('quiet')

github, warriner, predict_github, predict_google
['quiet', [-0.009000000000000008, -0.28600000000000003, -3.334], [1.863, 1.396, -3.814], [-0.03, 1.495, -1.393], [1.508, 2.093, -2.063]]


In [505]:
pprint('inactive')

github, warriner, predict_github, predict_google
['inactive', [-0.851, -0.394, -2.506], [-0.775, 0.346, -2.285], [-1.61, -0.491, -1.5], [-1.414, -0.616, -1.326]]


In [354]:
pprint('table')

github, warriner, predict_github, predict_google
['table', [0.99, 0.99, 0.872], [0.704, 1.452, -2.355], [0.7749999999999999, 0.697, -1.695], [0.895, 1.56, -2.077]]


In [58]:
pprint('log')

github, warriner, predict_github, predict_google
['log', [1.593, 1.114, 0.925], [0.053, -0.563, 1.258], [-0.267, 0.382, 1.419], [0.306, 1.505, 2.0]]


In [504]:
pprint('generate')

github, warriner, predict_github, predict_google
['generate', [0.79, 0.964, -0.9510000000000001], [1.473, 0.913, -0.966], [0.564, 1.508, -1.293], [1.053, 1.538, -0.462]]


In [33]:
pprint('invalid')

[0.202777778, -0.233333333, 0.377777778]
[-2.757554769515991, -1.9528812170028687, 0.18231704831123352]


In [36]:
pprint('typo')

['typo', [-0.862, -0.314, -0.068], [-1.375, -1.101, 1.205], [-1.317, -1.117, -0.61], [-0.94, -0.966, -0.76]]


In [80]:
pprint('filter')

['filter', [1.562962962962963, 0.8074074074074075, 0.9259259259259262], [-0.02104046568274498, 1.0362566709518433, -1.1613062620162964]]


In [36]:
pprint('system')

[2.074285714, 2.428571429, 2.111428571]
[0.6514638066291809, 0.847267746925354, -0.19178053736686707]


In [529]:
_wlist = set(label.keys()) & set(predict.keys()) & set(google.keys())
print(len(_wlist))
_wlist_label, _wlist_pred, _wlist_google = list(), list(), list()
_std = list()
for w in _wlist:
    _wlist_label.append(label[w])
    _wlist_pred.append(predict[w])
    _wlist_google.append(google[w])
    _std.append(label_std[w])
import numpy as np
_wlabel = np.array(_wlist_label)
_wpred = np.array(_wlist_pred)
_wgoogle = np.array(_wlist_google)
_wstd = np.array(_std)

print(np.sum(np.abs(_wlabel - _wpred) < _wstd, axis=0))
print(np.sum(np.abs(_wlabel - _wgoogle) < _wstd, axis=0))


mean = np.mean(np.abs(_wlabel - _wpred), axis=0)
print(mean)
rmse = np.sqrt(np.mean((_wlabel - _wpred) ** 2, axis=0))
print(rmse)
print('=========')
mean = np.mean(np.abs(_wlabel - _wgoogle), axis=0)
print(mean)
rmse = np.sqrt(np.mean((_wlabel - _wgoogle) ** 2, axis=0))
print(rmse)

428
[412 407 413]
[407 409 397]
[0.57892991 0.66439019 0.56442757]
[0.76819687 0.83325001 0.79286359]
[0.6392757  0.73421963 0.64543458]
[0.81261553 0.87929592 0.90952796]


In [541]:
epa_dic = {}
for w in wlist:
    def r(a):
        return [round(d, 2) for d in a]
    
    k = '%s & %s & %s & %s & %s \\\\' % (w, r(warriner[w]), r(label[w]), r(predict[w]), r(google[w]))
    epa_dic[k] = abs(label[w][0] - predict[w][0]) + abs(label[w][1] - predict[w][1]) \
    + abs(label[w][2] - predict[w][2])
from collections import OrderedDict
ordered_epa_dic = OrderedDict(sorted(epa_dic.items(), key=lambda x: x[1]))
for key in ordered_epa_dic:
    print(key)

port & [0.78, 1.56, -1.83] & [0.1, 0.68, -1.3] & [0.15, 0.74, -1.35] & [0.04, 0.79, -1.63] \\
option & [1.75, 2.17, -2.09] & [0.52, 1.12, -1.42] & [0.56, 0.87, -1.43] & [1.16, 1.54, -1.48] \\
core & [1.53, 1.52, -2.02] & [0.4, 0.69, -1.55] & [0.18, 0.76, -1.58] & [1.0, 1.86, -1.86] \\
android & [0.86, 1.33, -1.66] & [0.42, 0.9, -1.16] & [0.63, 0.99, -1.22] & [1.39, 1.37, -0.73] \\
chrome & [1.61, 0.64, -0.97] & [0.55, 1.23, -1.02] & [0.38, 1.17, -1.15] & [0.71, 1.13, -1.48] \\
hash & [-1.12, 0.22, -0.34] & [0.1, 0.41, -1.45] & [0.05, 0.69, -1.54] & [-0.41, 0.47, -1.36] \\
code & [-0.27, 0.06, -2.69] & [0.1, 0.64, -1.27] & [-0.07, 0.62, -1.52] & [0.4, 1.33, -1.5] \\
database & [-0.17, 1.84, -1.9] & [0.62, 1.04, -1.95] & [0.56, 1.04, -1.58] & [0.32, 1.24, -1.04] \\
matrix & [1.19, -0.29, -0.41] & [-0.39, 0.43, -1.28] & [-0.18, 0.43, -1.5] & [-0.04, 0.5, -1.72] \\
algorithm & [0.48, -1.04, -1.38] & [0.04, 0.49, -1.41] & [0.16, 0.58, -1.65] & [0.27, 0.73, -1.44] \\
super & [2.55, 2.93, -0.